#!/bin/bash

#Exibe as instruções do organizador automático de arquivos

echo "----------------------------------"
echo " Ajuda - Organizador de Arquivos"
echo "----------------------------------"
echo ""
echo "Opcções do menu:"
echo ""
echo " 1 - Organizar Dowloads"
echo "     Organiza os arquivos da pasta Dowloads"
echo ""
echo " 2 - Organizar outra pasta"
echo "     Pede o caminho de uma pasta e organiza os arquivos dela"
echo ""
echo " 3 - Mostrar estatísticas"
echo "     Mostra o total de arquivos já organizados, a contagem por tipo, a data da última organização e quais pastas já foram organizadas"
echo ""
echo " 4 - Desfazer última organização"
echo "     Devolve os arquivos movidos na última organização para o local original"
echo ""
echo " 5 - Ajuda"
echo "     Exibe esta tela"
echo ""
echo " 6 - Sair"
echo "     Encerra o programa"
echo ""
echo " -- Detalhes Importante --"
echo ""
echo " - Arquivos com nomes duplicados recebem um sufixo numérico;"
echo " - Arquivos sem extensão vão para uma subpasta chama Sem_Extensão;"
echo " - Só é possível desfazer a última organização realizada;"
echo " - Estatísticas são cumulativas e guardadas em historico.log"
echo ""
echo "----------------------------------"